version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo apt-get install lua5.1 luarocks
      - run:
          name: Download Lide Shell
          command: |
            git clone https://github.com/lidesdk/commandline.git $PWD/commandline --recursive &&
            sudo cp $PWD/commandline/clibs/linux/x64/pcaf_libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 &&
            sudo cp $PWD/commandline/clibs/linux/x64/pcaf_libzzip-0.so.13 /usr/lib/x86_64-linux-gnu/libzzip-0.so.13 &&
            chmod +x $PWD/commandline/bin/linux/x64/lua
      - run:
          name: Start Lide tests
          command: |
            $LIDE_PATH/lide.sh install lanes &&
