dependencies:
  pre:
    # install lua interpreter and luarocks
    - sudo apt-get install lua5.1 luarocks
    # install lide using latest rockspeck
    #- sudo luarocks install https://raw.githubusercontent.com/lidesdk/framework/master/lide-0.0-0.rockspec
    # install lide dependencis with luarocks
    #- sudo luarocks install luafilesystem

test:
  override:

    # Installation process:

        # xml necesita libstdc++6 (- sudo apt-get install libstdc++6)
        # zip necesita libzzip-0.so.13
        #- sudo cp $PWD/clibs/linux/x64/pcaf_libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        #- sudo cp $PWD/clibs/linux/x64/pcaf_libzzip-0.so.13 /usr/lib/x86_64-linux-gnu/libzzip-0.so.13

        # install latest framework version from master repo:
        - git clone https://github.com/lidesdk/commandline.git $PWD/commandline --recursive

        - sudo cp $PWD/commandline/clibs/linux/x64/pcaf_libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        - sudo cp $PWD/commandline/clibs/linux/x64/pcaf_libzzip-0.so.13 /usr/lib/x86_64-linux-gnu/libzzip-0.so.13 


        - chmod +x $PWD/commandline/bin/linux/x64/lua
        # - git clone https://github.com/lidesdk/framework.git $PWD/commandline/libraries/lide

        # authorize x64 lua interpreter:
        #- chmod +x $PWD/commandline/bin/linux/x64/lua

    # Executing tests:

        # executing the tests with default lua interpreter:
        # set Lide environment vars
        #- export LIDE_PATH=$PWD && lua5.1 tests/[linux]commandline_test.lua

        - $LIDE_PATH/lide.sh install lanes
        - $LIDE_PATH/lide.sh tests/appendud.lua
        - $LIDE_PATH/lide.sh tests/argtable.lua
        - $LIDE_PATH/lide.sh tests/assert.lua
        - $LIDE_PATH/lide.sh tests/atexit.lua
        - $LIDE_PATH/lide.sh tests/atomic.lua
        - $LIDE_PATH/lide.sh tests/basic.lua
        - $LIDE_PATH/lide.sh tests/cancel.lua